const theme = {
    color: {
        textColor: '#374658',
        linkColor: '#fb5192'
    },
    text: {
        fontFamilyRegular: "source-code-pro,Menlo,Monaco,Consolas,Courier New,monospace",
        fontFamilyHeading: "source-code-pro,Menlo,Monaco,Consolas,Courier New,monospace",
        fontFamilyLink: "source-code-pro,Menlo,Monaco,Consolas,Courier New,monospace",
        fontFamilyCode: "source-code-pro,Menlo,Monaco,Consolas,Courier New,monospace",
    },
    a: {
        margin:'0px',
        padding: '0px',
        alignItems: 'stretch',
        justifyContent: 'flex-start',
        flexGrow:'0',
        width:'auto',
        height:'auto',
        background:'transparent',
        radius:'0px',
        hoverBackground:'transparent',
        hoverColor:'#429ddd',
        hoverOpacity:'1',
        textDecoration:'underline',
        fontSize: '18px'
    },
    article: {
        width: '100%',
        minWidth: '0px',
        maxWidth: '768px',
        height: '100%',
        minHeight: '0px',
        maxHeight: 'none',
        display: 'flex',
        flexDirection: 'column',
        margin: '0 auto',
        padding: '0px',
        background: 'transparent',
        position: 'static',
        top: 'auto',
        bottom: 'auto',
        left: 'auto',
        right: 'auto',
        zIndex: 'auto',
        lineHeight: 'normal'
    },
    aside: {
        background: 'transparent',
        flexDirection: 'column',
        margin: '0px',
        padding: '0px',
        alignItems: 'stretch',
        justifyContent: 'flex-start',
        flexGrow: '0',
        width: 'auto',
        height: 'auto',
        minWidth: '0px',
        minHeight: '0px',
        maxWidth: 'none',
        maxHeight: 'none',
        position: 'static',
        top: 'auto',
        bottom: 'auto',
        left: 'auto',
        right: 'auto',
        zIndex: 'auto',
        fontSize: '18px'
    },
    button: {
        background: 'transparent',
        radius: '5px',
        justifyContent: 'center',
        alignItems: 'center',
        height: '40px',
        width: 'auto',
        minWidth: '0px',
        minHeight: '0px',
        maxWidth: 'none',
        maxHeight: 'none',
        color: '#000000',
        textTransform: 'uppercase',
        padding: '0px 15px',
        margin: '0px',
        boxShadow: 'none',
        hoverBackground: 'transparent',
        hoverColor: '#000000',
        hoverOpacity: '0.8',
        activeOpacity: '0.5'
    },
    column: {
        alignItems: 'stretch',
        justifyContent: 'flex-start',
        flexGrow: '0',
        background: 'transparent',
        height: 'auto',
        width: 'auto',
        minWidth: '0px',
        minHeight: '0px',
        maxWidth: 'none',
        maxHeight: 'none',
        padding: '0px',
        margin: '0px',
        cursor: 'auto',
        textAlign: 'left',
        boxShadow: 'none',
        position: 'static',
        top: 'auto',
        bottom: 'auto',
        left: 'auto',
        right: 'auto',
        zIndex: 'auto',
        flexWrap: 'nowrap',
        boxSizing: 'border-box',
        paddingMobile: '0px',
        marginMobile: '0px'
    },
    container: {
        flexDirection: 'row',
        background: 'transparent',
        maxWidth: '1440px',
        margin: '0 auto',
        padding: '0px',
        width: '100%',
        minHeight: '100vh'
    },
    divider: {
        height: '1px',
        color: '#45d4de',
        marginTop: '15px',
        marginBottom: '15px',
        width: '100%'
    },
    full: {
        background: 'rgba(0, 59, 74, 0.7)',
        padding: '20px 0px 20px 0px',
        margin: '15px 0px 15px 0px'
    },
    grid: {
        width: '100%',
        maxWidth: '1440px',
        columns: 'repeat(3, 1fr)',
        columnsTablet: 'repeat(3, 1fr)',
        columnsMobile: 'repeat(3, 1fr)',
        gap: '30px',
        padding: '0px',
        margin: '0 auto',
        minHeight: '0px',
        paddingMobile: '0px',
        marginMobile: '0px'
    },
    headingOne: {
        letterSpacing:'-2.5px',
        lineHeight: '68px',
        color:"#fb5192",
        margin: '0px',
        padding: '0px',
        textAlign: 'left',
        textTransform: 'none',
        fontWeight: '500',
        fontSize: '48px'
    },
    headingTwo: {
        letterSpacing:'0px',
        lineHeight: '1.25',
        color:"#fb5192",
        margin: '0px',
        padding: '0px',
        textAlign: 'left',
        textTransform: 'none',
        fontWeight: '200',
        fontSize: '32px'
    },
    headingThree: {
        letterSpacing:'0px',
        lineHeight: '1.1',
        color:"#fb5192",
        margin: '0px',
        padding: '0px',
        textAlign: 'left',
        textTransform: 'none',
        fontWeight: '500',
        fontSize: '28px',
        textShadow: 'none'
    },
    headingFour: {
        letterSpacing:'0px',
        lineHeight: '1.1',
        color:"#fb5192",
        margin: '0px',
        padding: '0px',
        textAlign: 'left',
        textTransform: 'none',
        fontWeight: '500',
        fontSize: '24px'
    },
    icon: {
        background: 'transparent',
        radius: '0px',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        color: '#000000',
        padding: '0px',
        margin: '0px',
        flexGrow: '0',
        fill: 'inherit',
        boxShadow: 'none',
        hoverBackground: 'transparent',
        hoverColor: '#000000',
        hoverOpacity: '0.8',
        activeOpacity: '0.5'
    },
    input: {
        margin:'0px 0px 15px 0px',
        height: '40px',
        border: 'none',
        background: '#EEEEEE',
        padding: '0px 10px 0px 10px',
        radius: '5px',
        width: '100%',
        fontSize: '18px',
        color: '#000000'
    },
    list: {
        maxWidth: '1024px',
        pointsType: 'disc',
        numbersType: 'decimal',
        margin: '0 auto',
        padding: '0px',
        flexDirection: 'column',
        justifyContent: 'stretch',
        alignItems: 'flex-start',
        flexWrap: 'nowrap'
    },
    listItem: {
        margin: '5px auto',
        padding: '0px',
        background: 'transparent',
        radius: '0px',
        width: '100%',
        height: 'auto',
        minWidth: '0px',
        minHeight: '0px',
        maxWidth: 'none',
        maxHeight: 'none',
        display: 'list-item',
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'stretch'
    },
    main: {
        background: 'transparent',
        margin: '0 auto',
        padding: '80px 16px 64px 16px',
        alignItems: 'stretch',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        width: '100%',
        height: 'auto',
        minWidth: '0px',
        minHeight: 'calc(100vh - 80px)',
        maxWidth: '1024px',
        maxHeight: 'none',
        paddingMobile: '0px',
        marginMobile: '0px'
    },
    media: {
        background: 'rgba(0, 59, 74, 0.7)',
        padding: '20px 0px 20px 0px',
        margin: '15px 0px 15px 0px',
        iframeHeight: '600px',
        iframeWidth: '768px'
    },
    p: {
        fontSize: '18px',
        lineHeight: '1.5',
        margin: '16px 0px 32px 0px',
        padding: '0px',
        fontWeight: 'normal',
        color: "#374658",
        textAlign: 'left',
        textTransform: 'none',
        wordBreak: 'break-word',
        wordWrap: 'break-word'
    },
    pre: {
        fontSize: '14px',
        margin: '0px 0px 20px 0px',
        padding: '20px',
        whiteSpace: 'pre-wrap',
        background: 'rgba(0, 59, 74, 0.7)',
        color: '#45d4de',
        lineHeight: '1.4',
        letterSpacing: '1px'
    },
    row: {
        alignItems: 'stretch',
        justifyContent: 'flex-start',
        flexGrow: '0',
        background: 'transparent',
        height: 'auto',
        width: 'auto',
        minWidth: '0px',
        minHeight: '0px',
        maxWidth: 'none',
        maxHeight: 'none',
        padding: '0px',
        margin: '0px',
        cursor: 'auto',
        textAlign: 'left',
        boxShadow: 'none',
        position: 'static',
        top: 'auto',
        bottom: 'auto',
        left: 'auto',
        right: 'auto',
        zIndex: 'auto',
        flexWrap: 'nowrap',
        boxSizing: 'border-box',
        paddingMobile: '0px',
        marginMobile: '0px'
    },
    section: {
        width: '100%',
        height: 'auto',
        minWidth: '0px',
        minHeight: '0px',
        maxWidth: 'none',
        maxHeight: 'none',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'stretch',
        margin: '0 auto',
        padding: '0px',
        background: 'transparent',
        backgroundSize: 'auto',
        backgroundPosition: '0% 0%',
        backgroundRepeat: 'repeat',
        position: 'static',
        top: 'auto',
        bottom: 'auto',
        left: 'auto',
        right: 'auto',
        zIndex: 'auto',
        lineHeight: 'normal',
        color: "#45d4de",
        boxShadow: 'none',
        radius: '0px',
        borderTop: 'none',
        borderBottom: 'none',
        borderLeft: 'none',
        borderRight: 'none',
        border: 'none',
        cursor: 'auto',
        opacity: '1'
    },
    select: {
        background: 'transparent',
        color: '#000000',
        width: '100%',
        height: 'auto',
        padding: '15px 10px',
        margin: '0px',
        border: '1px solid #000000',
        radius: '0px',
        maxHeight: 'none',
        listRadius:'0px',
        listShadow: '0px 0px 5px rgba(0, 0, 0, 0.1)',
        listBackground: '#FFFFFF',
        listColor: '#000000',
        listOffset: '55px',
        optionPadding: '15px 10px',
        optionHoverBackground: 'rgba(0, 0, 0, 0.1)',
        optionHoverOpacity: '1',
        optionHoverColor: '#000000',
        disabledOptionOpacity:'0.6',
        iconColor: '#777777'
    },
    span: {
        fontSize: '16px',
        color: '#374658',
        lineHeight: '1.5',
        margin: '0px',
        padding: '0px',
        fontWeight: 'normal',
        position: 'static',
        top: 'auto',
        bottom: 'auto',
        left: 'auto',
        right: 'auto',
        zIndex: 'auto',
        display: 'flex',
        flexDirection: 'row',
        alignItems:'stretch',
        justifyContent: 'flex-start',
        textAlign: 'left'
    },
    table: {
        border: '1px solid #000000',
        borderCollapse: 'collapse',
        borderSpacing: '2px',
        height: 'auto',
        width: 'auto',
        minWidth: '0px',
        minHeight: '0px',
        maxWidth: 'none',
        maxHeight: 'none',
        padding: '0px',
        margin: '0px',
        color: '#000000',
        cellWidth: 'auto',
        cellHeight: 'auto'
    },
    tag: {
        background: '#000000',
        radius:'4px',
        color: '#FFFFFF',
        padding: '3px 6px',
        margin: '10px 5px 0px 0px',
        fontSize: '18px'
    },
    header: {
        background:'#FFFFFF'
    },
    footer: {
        background:'#FFFFFF'
    },
}

export default theme